# Generated by Django 5.1.1 on 2025-02-08 16:45

import django.db.models.deletion
import extensions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='名称')),
                ('barcode', models.CharField(db_index=True, max_length=20, verbose_name='条码')),
                ('spec', models.CharField(blank=True, max_length=60, null=True, verbose_name='规格')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用状态')),
                ('enable_batch_control', models.BooleanField(db_index=True, default=False, verbose_name='批次控制')),
                ('expiration_days', models.IntegerField(null=True, verbose_name='有效期天数')),
                ('expiration_warning_days', models.IntegerField(null=True, verbose_name='有效期预警天数')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='删除状态')),
                ('delete_time', models.DateTimeField(db_index=True, null=True, verbose_name='删除时间')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_set', to='data.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_set', to='data.productcategory', verbose_name='产品分类')),
                ('supplier_set', models.ManyToManyField(blank=True, related_name='product_set', to='data.supplier', verbose_name='供应商')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.FloatField(null=True, verbose_name='采购单价')),
                ('sales_price', models.FloatField(null=True, verbose_name='销售单价')),
                ('level_price1', models.FloatField(null=True, verbose_name='等级价一')),
                ('level_price2', models.FloatField(null=True, verbose_name='等级价二')),
                ('level_price3', models.FloatField(null=True, verbose_name='等级价三')),
                ('total_quantity', models.FloatField(db_index=True, default=0, verbose_name='库存数量')),
                ('has_stock', models.BooleanField(db_index=True, default=False, verbose_name='库存状态')),
                ('is_on_sale', models.BooleanField(db_index=True, default=True, verbose_name='在售状态')),
                ('enable_warning', models.BooleanField(db_index=True, default=False, verbose_name='预警启用状态')),
                ('min_quantity', models.FloatField(null=True, verbose_name='最小数量')),
                ('max_quantity', models.FloatField(null=True, verbose_name='最大数量')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_set', to='system.warehouse', verbose_name='仓库')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_set', to='product.product', verbose_name='产品')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, verbose_name='编号')),
                ('total_quantity', models.FloatField(db_index=True, default=0, verbose_name='库存数量')),
                ('has_stock', models.BooleanField(db_index=True, default=False, verbose_name='库存状态')),
                ('production_date', models.DateField(db_index=True, null=True, verbose_name='生产日期')),
                ('warning_date', models.DateField(db_index=True, null=True, verbose_name='预警日期')),
                ('expiry_date', models.DateField(db_index=True, null=True, verbose_name='到期日期')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_set', to='system.warehouse', verbose_name='仓库')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_set', to='product.inventory', verbose_name='库存')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_set', to='product.product', verbose_name='产品')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='product_images', verbose_name='文件')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image_set', to='product.product', verbose_name='产品')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_set', to='product.productimage', verbose_name='主图'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=extensions.models.UniqueConstraintEx(fields=('warehouse', 'product'), name='inventory', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=extensions.models.UniqueConstraintEx(fields=('number', 'inventory', 'production_date'), name='batch', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=extensions.models.UniqueConstraintEx(fields=('name', 'spec', 'delete_time'), name='product', nulls_distinct=False),
        ),
    ]
