# Generated by Django 5.1.1 on 2024-12-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='启用状态'),
        ),
    ]
