# Generated by Django 5.1.1 on 2024-12-03 15:40

import django.db.models.deletion
import extensions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('permissions', models.JSONField(default=list, verbose_name='权限')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ModelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('model', models.CharField(choices=[('role', '角色权限'), ('user', '员工账号'), ('warehouse', '仓库管理'), ('account', '结算账户')], db_index=True, max_length=20, verbose_name='模型')),
                ('type', models.CharField(choices=[('text', '文本'), ('number', '数字'), ('date', '日期'), ('time', '时间'), ('single_choice', '单选'), ('multiple_choice', '多选')], max_length=20, verbose_name='类型')),
                ('priority', models.IntegerField(default=0, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('property', models.JSONField(default=dict, verbose_name='属性')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='删除状态')),
                ('delete_time', models.DateTimeField(db_index=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'constraints': [extensions.models.UniqueConstraintEx(fields=('name', 'model', 'delete_time'), name='ModelField.unique_name_model', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=120, verbose_name='密码')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('permissions', models.JSONField(default=list, verbose_name='权限')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('is_manager', models.BooleanField(default=False, verbose_name='管理员状态')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='激活状态')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='删除状态')),
                ('delete_time', models.DateTimeField(db_index=True, null=True, verbose_name='删除时间')),
                ('role_set', models.ManyToManyField(blank=True, related_name='user_set', to='system.role', verbose_name='角色')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('type', models.CharField(choices=[('info', '信息'), ('success', '成功'), ('warning', '警告'), ('error', '错误')], max_length=20, verbose_name='通知类型')),
                ('content', models.CharField(max_length=240, verbose_name='内容')),
                ('attachment', models.FileField(null=True, upload_to='', verbose_name='附件')),
                ('attachment_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='附件名称')),
                ('attachment_format', models.CharField(choices=[('excel', 'Excel 文件'), ('pdf', 'PDF 文件'), ('image', '图片文件')], max_length=20, null=True, verbose_name='附件格式')),
                ('has_attachment', models.BooleanField(default=False, verbose_name='附件状态')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='已读状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_set', to='system.user', verbose_name='通知人')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('address', models.CharField(blank=True, max_length=240, null=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('is_locked', models.BooleanField(db_index=True, default=False, verbose_name='锁定状态')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='激活状态')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='删除状态')),
                ('delete_time', models.DateTimeField(db_index=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'constraints': [extensions.models.UniqueConstraintEx(fields=('name', 'delete_time'), name='Warehouse.unique_name', nulls_distinct=False)],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='warehouse_set',
            field=models.ManyToManyField(blank=True, related_name='user_set', to='system.warehouse', verbose_name='仓库'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=extensions.models.UniqueConstraintEx(fields=('username', 'delete_time'), name='User.unique_username', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=extensions.models.UniqueConstraintEx(fields=('name', 'delete_time'), name='User.unique_name', nulls_distinct=False),
        ),
    ]
