# Generated by Django 5.1.1 on 2024-12-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='warehouse_set',
            field=models.ManyToManyField(blank=True, related_name='user_set', to='system.warehouse', verbose_name='授权仓库'),
        ),
    ]
