# Generated by Django 5.1.1 on 2025-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfield',
            name='source',
            field=models.CharField(choices=[('system', '系统'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='来源'),
        ),
    ]
