# Generated by Django 5.1.1 on 2024-12-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60, null=True, unique=True, verbose_name='编号')),
                ('model', models.CharField(choices=[('account', '结算账户')], db_index=True, max_length=20, verbose_name='模型')),
                ('export_id_list', models.JSONField(default=list, verbose_name='导出 ID 列表')),
                ('export_file', models.FileField(null=True, upload_to='', verbose_name='导出文件')),
                ('export_count', models.IntegerField(null=True, verbose_name='导出条数')),
                ('status', models.CharField(choices=[('exporting', '导出中'), ('cancelled', '已取消'), ('completed', '已完成'), ('failed', '导出失败')], db_index=True, default='exporting', max_length=32, verbose_name='导出状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('duration', models.IntegerField(null=True, verbose_name='耗时(秒)')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_task_set', to='system.user', verbose_name='创建人')),
            ],
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60, unique=True, verbose_name='任务编号')),
                ('model', models.CharField(choices=[('account', '结算账户')], db_index=True, max_length=20, verbose_name='模型')),
                ('import_file', models.FileField(upload_to='', verbose_name='导入文件')),
                ('import_count', models.IntegerField(null=True, verbose_name='导入条数')),
                ('status', models.CharField(choices=[('importing', '导入中'), ('cancelled', '已取消'), ('completed', '已完成'), ('failed', '导入失败')], db_index=True, default='importing', max_length=32, verbose_name='导入状态')),
                ('error_message_list', models.JSONField(default=list, verbose_name='错误信息')),
                ('duration', models.IntegerField(null=True, verbose_name='耗时(秒)')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_task_set', to='system.user', verbose_name='创建人')),
            ],
        ),
    ]
