# Generated by Django 5.1.1 on 2025-01-13 15:29

import django.db.models.deletion
import extensions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用状态')),
                ('initial_balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='初期余额')),
                ('balance_amount', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, verbose_name='余额')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='删除状态')),
                ('delete_time', models.DateTimeField(db_index=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'constraints': [extensions.models.UniqueConstraintEx(fields=('name', 'delete_time'), name='Account.unique_name', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('level', models.CharField(choices=[('lv0', '普通客户'), ('lv1', '一级客户'), ('lv2', '二级客户'), ('lv3', '三级客户')], db_index=True, default='lv0', max_length=20, verbose_name='客户等级')),
                ('contact', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('address', models.CharField(blank=True, max_length=240, null=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用状态')),
                ('initial_arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='初期欠款金额')),
                ('arrears_amount', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, verbose_name='欠款金额')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='删除状态')),
                ('delete_time', models.DateTimeField(db_index=True, null=True, verbose_name='删除时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_set', to='data.clientcategory', verbose_name='客户分类')),
            ],
            options={
                'constraints': [extensions.models.UniqueConstraintEx(fields=('name', 'delete_time'), name='Client.unique_name', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('contact', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('address', models.CharField(blank=True, max_length=240, null=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=240, null=True, verbose_name='备注')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用状态')),
                ('initial_arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='初期欠款金额')),
                ('arrears_amount', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, verbose_name='欠款金额')),
                ('extension_data', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='删除状态')),
                ('delete_time', models.DateTimeField(db_index=True, null=True, verbose_name='删除时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_set', to='data.suppliercategory', verbose_name='供应商分类')),
            ],
            options={
                'constraints': [extensions.models.UniqueConstraintEx(fields=('name', 'delete_time'), name='Supplier.unique_name', nulls_distinct=False)],
            },
        ),
    ]
