# Generated by Django 5.1.1 on 2025-01-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_account_is_active_remove_client_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_exporting',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_importing',
        ),
    ]
