# Generated by Django 5.1.1 on 2025-01-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_account_is_exporting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='extension_data',
            field=models.JSONField(default=dict, null=True, verbose_name='扩展数据'),
        ),
    ]
