# Generated by Django 5.1.1 on 2025-01-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_account_extension_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='extension_data',
            field=models.JSONField(default=dict, verbose_name='扩展数据'),
        ),
    ]
